# Generated by Django 4.2.1 on 2025-06-03 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_cabinet_id_alter_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата'),
        ),
    ]
